version: "3.9"
services:
  db:
    image: postgres:16
    container_name: rcapi-db
    environment:
      POSTGRES_DB: contentsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d contentsdb"]
      interval: 5s
      timeout: 5s
      retries: 10



  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rcapi-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contentsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_ADDITIONAL_LOCATION: /config/
    ports:
      - "8080:8080"
    env_file:
      - ./app.env


volumes:
  - ./config:/config:
