server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://172.27.208.1:5432/contentsdb?reWriteBatchedInserts=true
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  contents:
    files:
      base-dir: "${USERPROFILE}/Desktop/Internproject/images"


springdoc:
  swagger-ui:
    path: /swagger-ui/index.html