server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contentsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html